version: "3.7"

services:
  keycloak:
    image: quay.io/keycloak/keycloak
    ports:
      - 8080:8080
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: keycloak_mysql
      DB_USER: root
      DB_PASSWORD: root
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    container_name: keycloak
    depends_on:
      keycloak_mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "http://localhost:8080/auth/realms/yata/protocol/openid-connect/certs"]
      interval: 10s
      retries: 20

  keycloak_mysql:
    image: mysql:5.7
    volumes:
      - ./volumes/keycloak:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
    container_name: keycloak_mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      retries: 20
